name: Release Electron development
on:
  push:
    branches:
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_INFURA_URL: https://kovan.infura.io/v3/number123    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' >> .npmrc
      - run: npm install
      - run: npm run test
  release_osx:
    permissions: write-all
    needs: test
    runs-on: macOS-latest
    environment: development
    env:
      REACT_APP_INFURA_URL: ${{secrets.INFURA_URL}}
      REACT_APP_ROOT_DOMAIN_ID: ${{secrets.ROOT_DOMAIN_ID}}
      REACT_APP_DEFAULT_ZNS_DOMAIN: ${{secrets.DEFAULT_ZNS_DOMAIN}}
      REACT_APP_DEFAULT_APP: ${{secrets.DEFAULT_APP}}
      REACT_APP_IPFS_BASE_URL: ${{secrets.IPFS_BASE_URL}}
      REACT_APP_FORTMATIC_API_KEY: ${{secrets.FORTMATIC_API_KEY}}
      REACT_APP_PORTIS_DAPP_ID: ${{secrets.PORTIS_DAPP_ID}}
      REACT_APP_INFURA_ID: ${{secrets.INFURA_ID}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' >> .npmrc
      - run: npm install
      - name: Build/Release Electron Zer0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:package:mac:publish
